package tools;

/**
 *
 * @author Mateus
 */
import java.nio.file.*;
import java.io.IOException;

public class ManipuladorArquivosHTML {

    private String diretorio;

    public ManipuladorArquivosHTML(String diretorio) {
        this.diretorio = diretorio;
    }

    public void escreverArquivo(String nomeArquivo, String conteudo) {
        Path path = Paths.get("D:\\documentos\\GitHub\\Mugen-Project-2\\arquivo.html");
        try {
            Files.write(path, conteudo.getBytes());
        } catch (IOException e) {
            System.out.println("Erro ao escrever o arquivo: " + e.getMessage());
        }
    }

    public void excluirArquivo(String nomeArquivo) {
        Path path = Paths.get("D:\\documentos\\GitHub\\Mugen-Project-2\\");
        try {
            Files.deleteIfExists(path);
        } catch (IOException e) {
            System.out.println("Erro ao excluir o arquivo: " + e.getMessage());
        }
    }

    public static void main(String name, String age, String altura, String peso, String raca, String filiacao, String jujutsu, String grade, String arma) {
        ManipuladorArquivosHTML manipulador = new ManipuladorArquivosHTML("D:\\documentos\\GitHub\\Mugen-Project-2\\");

        manipulador.escreverArquivo("arquivo.html", "<!DOCTYPE html>\n"
                + "<html lang=\"pt-BR\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\"/>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n"
                + "    <title>Ficha de Personagem - Jujutsu Kaisen</title>\n"
                + "\n"
                + "    <style>\n"
                + "        @import url('https://fonts.googleapis.com/css2?family=Homemade+Apple');\n"
                + "        @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@600');\n"
                + "\n"
                + "        @font-face {\n"
                + "            font-family: 'Jujutsu Kaisen';\n"
                + "            src: url('/ficha/Jujutsu_Kaisen.ttf');\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            font-family: 'Jujutsu Kaisen', 'Homemade Apple', cursive;\n"
                + "            background-color: #ffffff;\n"
                + "            color: #333;\n"
                + "            margin: 20px;\n"
                + "            font-size: 20px;\n"
                + "            display: flex;\n"
                + "            flex-direction: column;\n"
                + "            align-items: center;\n"
                + "        }\n"
                + "\n"
                + "        h1 {\n"
                + "            font-size: 30px;\n"
                + "        }\n"
                + "\n"
                + "        h2 {\n"
                + "            font-size: 20px;\n"
                + "            align-self: center;\n"
                + "        }\n"
                + "\n"
                + "        p {\n"
                + "            font-family: 'Homemade Apple', cursive;\n"
                + "        }\n"
                + "\n"
                + "        header {\n"
                + "            text-align: center;\n"
                + "            color: #ff5555;\n"
                + "            padding: 10px;\n"
                + "            margin-bottom: 20px;\n"
                + "        }\n"
                + "\n"
                + "        section {\n"
                + "            display: flex;\n"
                + "            flex-direction: row;\n"
                + "            gap: 10px;\n"
                + "            margin-bottom: 20px;\n"
                + "        }\n"
                + "\n"
                + "        .character-info {\n"
                + "            flex: 1 1 calc(50% - 10px);\n"
                + "            display: flex;\n"
                + "            flex-direction: column;\n"
                + "            box-sizing: border-box;\n"
                + "            background-color: #e7e7e7;\n"
                + "            border: 2px solid #ccc;\n"
                + "            border-radius: 8px;\n"
                + "            margin-bottom: 20px;\n"
                + "            padding: 20px;\n"
                + "        }\n"
                + "\n"
                + "        .character-info>div {\n"
                + "            margin-bottom: 5px;\n"
                + "        }\n"
                + "\n"
                + "        label {\n"
                + "            display: block;\n"
                + "            margin-bottom: 10px;\n"
                + "            color: #000000;\n"
                + "        }\n"
                + "\n"
                + "        p {\n"
                + "            padding: 7px;\n"
                + "            margin-bottom: 10px;\n"
                + "            background-color: #f5f5f5;\n"
                + "            border: 1px solid #a8a8a8;\n"
                + "            border-radius: 4px;\n"
                + "        }\n"
                + "\n"
                + "        footer {\n"
                + "            text-align: center;\n"
                + "            margin-top: 20px;\n"
                + "            color: #808080;\n"
                + "            width: 71%;\n"
                + "        }\n"
                + "\n"
                + "        .container {\n"
                + "            display: flex;\n"
                + "            flex-direction: column;\n"
                + "        }\n"
                + "\n"
                + "        .name{\n"
                + "            font-family: 'Times New Roman', Times, serif;\n"
                + "            font-size: 16px;\n"
                + "        }\n"
                + "\n"
                + "        @media (max-width: 768px) {\n"
                + "            section {\n"
                + "                flex-direction: column;\n"
                + "            }\n"
                + "\n"
                + "            .character-info {\n"
                + "                flex: 1 1 100%;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "    <header>\n"
                + "        <h1>Ficha de Personagem - Mugen Project</h1>\n"
                + "    </header>\n"
                + "\n"
                + "    <div class=\"container\">\n"
                + "\n"
                + "        <section style=\"width: 100%;\">\n"
                + "            <div class=\"character-info\">\n"
                + "                <div>\n"
                + "                    <label for=\"name\">Nome:</label>\n"
                + "                    <p name=\"name\">" + name + "</p>\n"
                + "                </div>\n"
                + "\n"
                + "                <div>\n"
                + "                    <label for=\"age\">Idade:</label>\n"
                + "                    <p name=\"age\">" + age + "</p>\n"
                + "                </div>\n"
                + "\n"
                + "                <div>\n"
                + "                    <label for=\"height\">Altura (cm):</label>\n"
                + "                    <p name=\"height\">" + altura + "</p>\n"
                + "                </div>\n"
                + "\n"
                + "                <div >\n"
                + "                    <label for=\"weight\">Peso (kg):</label>\n"
                + "                    <p name=\"weight\">" + peso + "</p>\n"
                + "                </div>\n"
                + "\n"
                + "                <div>\n"
                + "                    <label for=\"race\">Raca:</label>\n"
                + "                    <p name=\"race\">" + raca + "</p>\n"
                + "                </div>\n"
                + "\n"
                + "                <div>\n"
                + "                    <label for=\"parentage\">Filiacao:</label>\n"
                + "                    <p name=\"parentage\">" + filiacao + "</p>\n"
                + "                </div>\n"
                + "\n"
                + "                <div>\n"
                + "                    <label for=\"curse-type\">Tipo de Maldicao:</label>\n"
                + "                    <p name=\"curse-type\">" + jujutsu + "</p>\n"
                + "                </div>\n"
                + "\n"
                + "                <div>\n"
                + "                    <label for=\"grade\">Grade:</label>\n"
                + "                    <p name=\"grade\">" + grade + "</p>\n"
                + "                </div>\n"
                + "\n"
                + "                <div>\n"
                + "                    <label for=\"weapon\">Arma:</label>\n"
                + "                    <p name=\"weapon\">" + arma + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </section>\n"
                + "\n"
                + "        <div style=\"width: 2%;\"></div>\n"
                + "\n"
                + "        <div style=\"width: 100%; display: flex; flex-direction: row;\">\n"
                + "            <section style=\"height: 50%;\">\n"
                + "                <div class=\"character-info\">\n"
                + "                    <h2>Aparencia</h2>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "\n"
                + "                </div>\n"
                + "            </section>\n"
                + "\n"
                + "            <section style=\"height: 50%;\">\n"
                + "                <div class=\"character-info\">\n"
                + "                    <h2>Historia e Detalhes</h2>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "                    <br/>\n"
                + "\n"
                + "                </div>\n"
                + "            </section>\n"
                + "        </div>\n"
                + "    </div>\n"
                + "    <footer class=\"text-muted\">\n"
                + "        <p class=\"name\">&copy; 2023 Mateus Batichotti 'Cohuzer' Silva</p>\n"
                + "    </footer>\n"
                + "</body>\n"
                + "</html>");
    }
}
